

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Joshua
 */
import javax.swing.JOptionPane;
import java.awt.*;
import javax.swing.Timer;
public class home extends javax.swing.JFrame {

    private int z = 0;
    private int yButton = 0;
    private int project_key;
    private boolean journalEntryUsed = false;
    private boolean ledgerIsUsed = false;
    private boolean UTBIsOpen = false;
    private boolean ATBIsOpen = false;
    private boolean doLoadAdjustments = false;
    private boolean SFPisOpen = false;
    private boolean SPLisOpen = false;
    
    journalEntry je;
    UnadjustTB UTB;
    Ledger ld;
    Adjustments ad;
    AdjustedTB ATB;
    SFPosition SFP;
    SProfitOrLoss SPL;
    
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        jButton3.setVisible(false);
        jButton1.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton8.setVisible(false);
        jButton9.setVisible(false);
        jButton10.setVisible(false);
        jButton11.setVisible(false);
        jButton12.setVisible(false);
        
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        
        ld = new Ledger(this);
        je = new journalEntry(this, ld);  
        UTB = new UnadjustTB(this);
        ad = new Adjustments(this, ld);
        ATB = new AdjustedTB(this);
        SFP = new SFPosition(this);
        SPL = new SProfitOrLoss(this);
        
        
        UTBWindowListener();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Accounting Cycle Management System");
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1366, 781));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1366, 781));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/control hide and show.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_icon.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jButton3ComponentShown(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/journal_entry_icon.png"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jButton4ComponentShown(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ledger_icon.png"))); // NOI18N
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jButton5ComponentShown(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unadjustd_trial_balance_icon.png"))); // NOI18N
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jButton6ComponentShown(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adjustments_icon.png"))); // NOI18N
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7MouseExited(evt);
            }
        });
        jButton7.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jButton7ComponentShown(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adjusted_trial_balance_icon.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jButton1ComponentShown(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, -1, -1));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/export_icon.png"))); // NOI18N
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton8MouseExited(evt);
            }
        });
        jButton8.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jButton8ComponentShown(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, -1, -1));

        jButton11.setText("Financial Statement of Financial Position");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 450, 400));

        jButton12.setText("Financial Statement of Profit or Loss");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 450, 400));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton9MouseExited(evt);
            }
        });
        jButton9.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jButton9ComponentShown(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 50, -1, -1));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit button.png"))); // NOI18N
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton10MouseExited(evt);
            }
        });
        jButton10.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jButton10ComponentShown(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 50, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Show/Hide");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Home");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 64, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Journal ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 66, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Ledger");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 66, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("UTB");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 66, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Adjustment");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ATB");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 64, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("FS");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 68, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Logout");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 120, 66, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Close");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 120, 66, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_background.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void UTBWindowListener() {

         
        this.addWindowStateListener(e -> {
            // UTB handling
            if (UTBIsOpen && UTB != null) {
                if ((e.getNewState() & Frame.ICONIFIED) == Frame.ICONIFIED) {
                    UTB.setVisible(false); // hide UTB when parent minimized
                } else if ((e.getNewState() & Frame.NORMAL) == Frame.NORMAL) {
                    UTB.setVisible(true);  // restore UTB when parent restored
                }
            }

            // ATB handling
            if (ATBIsOpen && ATB != null) {
                if ((e.getNewState() & Frame.ICONIFIED) == Frame.ICONIFIED) {
                    ATB.setVisible(false); // hide ATB when parent minimized
                } else if ((e.getNewState() & Frame.NORMAL) == Frame.NORMAL) {
                    ATB.setVisible(true);  // restore ATB when parent restored
                }
            }
            if(yButton == 1) {
                if ((e.getNewState() & Frame.ICONIFIED) == Frame.ICONIFIED) {
                    jButton11.setVisible(false); // hide ATB when parent minimized
                    jButton12.setVisible(false);
                } else if ((e.getNewState() & Frame.NORMAL) == Frame.NORMAL) {
                    jButton11.setVisible(true); // hide ATB when parent minimized
                    jButton12.setVisible(true);  // restore ATB when parent restored
                }
            }
            if (SFPisOpen && SFP != null) {
                if ((e.getNewState() & Frame.ICONIFIED) == Frame.ICONIFIED) {
                    SFP.setVisible(false); // hide ATB when parent minimized
                } else if ((e.getNewState() & Frame.NORMAL) == Frame.NORMAL) {
                    SFP.setVisible(true);  // restore ATB when parent restored
                }
            }
            if (SPLisOpen && SPL != null) {
                if ((e.getNewState() & Frame.ICONIFIED) == Frame.ICONIFIED) {
                    SPL.setVisible(false); // hide ATB when parent minimized
                } else if ((e.getNewState() & Frame.NORMAL) == Frame.NORMAL) {
                    SPL.setVisible(true);  // restore ATB when parent restored
                }
            }
        });
    }

    public void setProjectKey(int key) {
        this.project_key = key;
    }
    public void setDoLoad(boolean load) {
        this.doLoadAdjustments = load;
    }
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if(UTBIsOpen) {
            UTB.dispose();
            UTB = null;
            UTBIsOpen = false;
        }
        if(ATBIsOpen) {
            ATB.dispose();
            ATB = null;
            ATBIsOpen = false; 
        }
        if(SFPisOpen) {
            SFP.dispose();
            SFP = null;
            SFPisOpen = false;
        }
        if(SPLisOpen) {
            SPL.dispose();
            SPL = null;
            SPLisOpen = false;
        }
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to close the program?","Select", JOptionPane.YES_NO_OPTION);
        if(a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(UTBIsOpen) {
            UTB.dispose();
            UTB = null;
            UTBIsOpen = false;
            return;
        }
        if(ATBIsOpen) {
            ATB.dispose();
            ATB = null;
            return;
        }
        if(SFPisOpen) {
            SFP.dispose();
            SFP = null;
            SFPisOpen = false;
            return;
        }
        if(SPLisOpen) {
            SPL.dispose();
            SPL = null;
            SPLisOpen = false;
            return;
        }
        JOptionPane.showMessageDialog(null, "You're in the home page already!", "Press OK", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if(UTBIsOpen) {
            UTB.dispose();
            UTB = null;
            UTBIsOpen = false;
        }
        if(ATBIsOpen) {
            ATB.dispose();
            ATB = null;
            ATBIsOpen = false;
        }
        if(SFPisOpen) {
            SFP.dispose();
            SFP = null;
            SFPisOpen = false;
        }
        if(SPLisOpen) {
            SPL.dispose();
            SPL = null;
            SPLisOpen = false;
            return;
        }
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to logout?","Select", JOptionPane.YES_NO_OPTION);
        if(a == 0) {
            setVisible(false);
            new login().setVisible(true);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        if(z == 0) 
        {
            try{
                Thread.sleep(100);
                jButton3.setVisible(true);
            }catch(Exception e) {
            
            }
        } else {
        jButton3.setVisible(false);
        jButton1.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton8.setVisible(false);
        jButton9.setVisible(false);
        jButton10.setVisible(false);
        
        z = 0;
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton3ComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(10);
                jButton4.setVisible(true);
            }catch(Exception e) {
            
            }
    }//GEN-LAST:event_jButton3ComponentShown

    private void jButton4ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton4ComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(10);
                jButton5.setVisible(true);
            }catch(Exception e) {
            
            }
    }//GEN-LAST:event_jButton4ComponentShown

    private void jButton5ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton5ComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(10);
                jButton6.setVisible(true);
            }catch(Exception e) {
            
            }
    }//GEN-LAST:event_jButton5ComponentShown

    private void jButton6ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton6ComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(10);
                jButton7.setVisible(true);
            }catch(Exception e) {
            
            }
    }//GEN-LAST:event_jButton6ComponentShown

    private void jButton7ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton7ComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(10);
                jButton1.setVisible(true);
            }catch(Exception e) {
            
            }
    }//GEN-LAST:event_jButton7ComponentShown

    private void jButton1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton1ComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(10);
                jButton8.setVisible(true);
            }catch(Exception e) {
            
            }
    }//GEN-LAST:event_jButton1ComponentShown

    private void jButton8ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton8ComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(10);
                jButton9.setVisible(true);
            }catch(Exception e) {
            
            }
    }//GEN-LAST:event_jButton8ComponentShown

    private void jButton9ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton9ComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(10);
                jButton10.setVisible(true);
            }catch(Exception e) {
            
            }
    }//GEN-LAST:event_jButton9ComponentShown

    private void jButton10ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton10ComponentShown
        // TODO add your handling code here:
        z = 1;
    }//GEN-LAST:event_jButton10ComponentShown

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(UTBIsOpen) {
            UTB.dispose();
            UTB = null;
            UTBIsOpen = false;
            return;
        }
        if(ATBIsOpen) {
            ATB.dispose();
            ATB = null;
            ATBIsOpen = false;
            return;
        }
        if(SFPisOpen) {
            SFP.dispose();
            SFP = null;
            SFPisOpen = false;
            return;
        }
        if(SPLisOpen) {
            SPL.dispose();
            SPL = null;
            SPLisOpen = false;
            return;
        }
        setVisible(false);
        
        if(!journalEntryUsed) {
            je.setVisible(true);
            AskForAddDetails dialogue = new AskForAddDetails(this, je);
            dialogue.setModal(true);
            dialogue.setVisible(true);
            
            this.project_key = je.getProjectId();
            
            journalEntryUsed = true;
        } else {
            je.setVisible(true);
            je.setProjectId(project_key, true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(!journalEntryUsed) {
            JOptionPane.showMessageDialog(null, "There is no journal entry, unadjusted trial balance can't be used!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!ledgerIsUsed) {
            JOptionPane.showMessageDialog(null, "Use ledger first! Unadjusted trial balance can't be used!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(ATBIsOpen) {
            ATB.dispose();
            ATB = null;
            ATBIsOpen = false;
            return;
        }
        if(SFPisOpen) {
            SFP.dispose();
            SFP = null;
            SFPisOpen = false;
            return;
        }
        if(SPLisOpen) {
            SPL.dispose();
            SPL = null;
            SPLisOpen = false;
            return;
        }
        if(!UTBIsOpen) {
            if (UTB == null) // ✅ recreate if disposed
                UTB = new UnadjustTB(this);
            int parentX = this.getX();
            int parentY = this.getY();
            UTB.setVisible(true);
            UTB.setLocation(new java.awt.Point(parentX + 290, parentY + 170));
            UTB.setProjectId(project_key);
            UTB.loadUTB();
            UTBIsOpen = true;
        } else {
            UTB.dispose();
            UTB = null;
            UTBIsOpen = false;
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(!journalEntryUsed) {
            JOptionPane.showMessageDialog(null, "There is no journal entry, adjustments can't be used!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!ledgerIsUsed)  {
            JOptionPane.showMessageDialog(null, "Use ledger first!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(UTBIsOpen) {
            UTB.dispose();
            UTB = null;
            UTBIsOpen = false;
            return;
        }
        if(ATBIsOpen) {
            ATB.dispose();
            ATB = null;
            ATBIsOpen = false;
            return;
        }
        if(SFPisOpen) {
            SFP.dispose();
            SFP = null;
            SFPisOpen = false;
            return;
        }
        if(SPLisOpen) {
            SPL.dispose();
            SPL = null;
            SPLisOpen = false;
            return;
        }
        ad.setProjectId(project_key, doLoadAdjustments);
        ad.setVisible(true);
        
    }//GEN-LAST:event_jButton7ActionPerformed
    private void animateExpandWithImpact(javax.swing.JButton button, int targetWidth, int targetHeight) {
        button.setVisible(true);
        button.setBounds(button.getX(), button.getY(), 0, 0); // start tiny
        final int x = button.getX();
        final int y = button.getY();
        Timer timer = new Timer(15, null); // ~60fps

        timer.addActionListener(new java.awt.event.ActionListener() {
            int w = 0, h = 0;
            int phase = 0; // 0 = grow, 1 = overshoot, 2 = settle, 3 = shake
            int shakeCount = 0;

            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                switch (phase) {
                    case 0:  
                        if (w < targetWidth || h < targetHeight) {
                            w = Math.min(w + 6, targetWidth);
                            h = Math.min(h + 6, targetHeight);
                            button.setBounds(x, y, w, h);
                        } else {
                            phase = 1;  
                        }
                        break;

                    case 1:  
                        w = targetWidth + 10;
                        h = targetHeight + 5;
                        button.setBounds(x, y, w, h);
                        phase = 2;
                        break;

                    case 2:  
                        w = targetWidth;
                        h = targetHeight;
                        button.setBounds(x, y, w, h);
                        phase = 3;  
                        break;

                    case 3:  
                        if (shakeCount < 6) {
                            int offset = (shakeCount % 2 == 0 ? 5 : -5);
                            button.setLocation(x + offset, y);
                            shakeCount++;
                        } else {
                            button.setLocation(x, y); 
                            ((Timer) e.getSource()).stop();
                        }
                        break;
                }

                button.revalidate();
                button.repaint();
            }
        });

        timer.start();
    }

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(!journalEntryUsed) {
            JOptionPane.showMessageDialog(null, "No financial statement!, open or create entries first!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(UTBIsOpen) {
            UTB.dispose();
            UTB = null;
            UTBIsOpen = false;
            return;
        }
        if(ATBIsOpen) {
            ATB.dispose();
            ATB = null;
            ATBIsOpen = false;
            return;
        }
        if(SFPisOpen) {
            SFP.dispose();
            SFP = null;
            SFPisOpen = false;
            return;
        }
        if(SPLisOpen) {
            SPL.dispose();
            SPL = null;
            SPLisOpen = false;
            return;
        }
        if (yButton == 0) {
            animateExpandWithImpact(jButton11, 450, 400);  
            animateExpandWithImpact(jButton12, 450, 400);
            yButton = 1;
        } else {
            jButton11.setVisible(false);
            jButton12.setVisible(false);
            yButton = 0;
        }
     
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        jLabel4.setVisible(true);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
        jLabel4.setVisible(false);
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
        jLabel5.setVisible(true);
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add your handling code here:
        jLabel5.setVisible(false);
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
        jLabel6.setVisible(true);
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        // TODO add your handling code here:
        jLabel6.setVisible(false);
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        // TODO add your handling code here:
        jLabel7.setVisible(true);
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        // TODO add your handling code here:
        jLabel7.setVisible(false);
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        // TODO add your handling code here:
        jLabel8.setVisible(true);
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        // TODO add your handling code here:
        jLabel8.setVisible(false);
    }//GEN-LAST:event_jButton6MouseExited

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
        // TODO add your handling code here:
        jLabel9.setVisible(true);
    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseExited
        // TODO add your handling code here:
        jLabel9.setVisible(false);
    }//GEN-LAST:event_jButton7MouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jLabel10.setVisible(true);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jLabel10.setVisible(false);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseEntered
        // TODO add your handling code here:
        jLabel11.setVisible(true);
    }//GEN-LAST:event_jButton8MouseEntered

    private void jButton8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseExited
        // TODO add your handling code here:
        jLabel11.setVisible(false);
    }//GEN-LAST:event_jButton8MouseExited

    private void jButton9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseEntered
        // TODO add your handling code here:
        jLabel12.setVisible(true);
    }//GEN-LAST:event_jButton9MouseEntered

    private void jButton9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseExited
        // TODO add your handling code here:
        jLabel12.setVisible(false);
    }//GEN-LAST:event_jButton9MouseExited

    private void jButton10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseEntered
        // TODO add your handling code here:
        jLabel13.setVisible(true);
    }//GEN-LAST:event_jButton10MouseEntered

    private void jButton10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseExited
        // TODO add your handling code here:
        jLabel13.setVisible(false);
    }//GEN-LAST:event_jButton10MouseExited
    
    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton4MouseClicked
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:   
        if(!journalEntryUsed) {
            JOptionPane.showMessageDialog(null, "There is no journal entry, ledger can't be used!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(UTBIsOpen) {
            UTB.dispose();
            UTB = null;
            UTBIsOpen = false;
            return;
        }
        if(ATBIsOpen) {
            ATB.dispose();
            ATB = null;
            ATBIsOpen = false;
            return;
        }
        if(SFPisOpen) {
            SFP.dispose();
            SFP = null;
            SFPisOpen = false;
            return;
        }
        if(SPLisOpen) {
            SPL.dispose();
            SPL = null;
            SPLisOpen = false;
            return;
        }
        if(!ledgerIsUsed) {
            ledgerIsUsed = true;
        }
        ld.setProjectId(project_key);
        System.out.println(project_key);
        
       
        setVisible(false);
        ld.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!journalEntryUsed) {
            JOptionPane.showMessageDialog(null, "There is no journal entry, adjusted trial balance can't be used!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!ledgerIsUsed) {
            JOptionPane.showMessageDialog(null, "Use ledger first! Adjusted trial balance can't be used!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(UTBIsOpen) {
            UTB.dispose();
            UTB = null;
            UTBIsOpen = false;
            return;
        }
        if(SFPisOpen) {
            SFP.dispose();
            SFP = null;
            SFPisOpen = false;
            return;
        }
        if(SPLisOpen) {
            SPL.dispose();
            SPL = null;
            SPLisOpen = false;
            return;
        }
        if(!ATBIsOpen) {
            if (ATB == null) // ✅ recreate if disposed
                ATB = new AdjustedTB(this);
            int parentX = this.getX();
            int parentY = this.getY();
            ATB.setVisible(true);
            ATB.setLocation(new java.awt.Point(parentX + 290, parentY + 170));
            ATB.setProjectId(project_key);
            ATB.isAdjustmentUsed();
            ATB.loadATB();
            ATBIsOpen = true;
        } else {
            ATB.dispose();
            ATB = null;
            ATBIsOpen = false;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        if(yButton == 1) {
            jButton11.setVisible(false);
            jButton12.setVisible(false);
            yButton = 0;
        }
        if(!SPLisOpen) {
            if (SPL == null) //  
                SPL = new SProfitOrLoss(this);
            int parentX = this.getX();
            int parentY = this.getY();
            int parentWidth = this.getWidth();

            int childWidth = SPL.getWidth();  
            int centerX = parentX + (parentWidth - childWidth) / 2;

            SPL.setLocation(centerX, parentY + 170);  
            SPL.setVisible(true); 
            SPL.setProjectId(project_key);
            SPL.loadIncomeStatement();
            SPLisOpen = true;
        } else {
            SPL.dispose();
            SPL = null;
            SPLisOpen = false;
        }
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        if(yButton == 1) {
            jButton11.setVisible(false);
            jButton12.setVisible(false);
            yButton = 0;
        }
        if(!SFPisOpen) {
            if (SFP == null) //  
                SFP = new SFPosition(this);
            int parentX = this.getX();
            int parentY = this.getY();
            int parentWidth = this.getWidth();

            int childWidth = SFP.getWidth();  
            int centerX = parentX + (parentWidth - childWidth) / 2;

            SFP.setLocation(centerX, parentY + 170);  
            SFP.setVisible(true); 
            SFP.setProjectId(project_key);
            SFP.loadFPostion();
            SFPisOpen = true;
        } else {
            SFP.dispose();
            SFP = null;
            SFPisOpen = false;
        }
        
    }//GEN-LAST:event_jButton11ActionPerformed
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
